POST http://localhost:3000/remote
Content-Type: application/json

{
    "status": "play",
    "volume": 100,
    "addmode": "play",
    "time": 0,
    "media": {
        "service": "youtube",
        //"path": "https://www.youtube.com/watch?v=fWNaR-rxAic&ab_channel=CarlyRaeJepsenVEVO"
        "path": "./vid/sample.mp4"
    }
}
//{
//  "status": "pause", // pause, play
//  "move": "next", // end, next
//  "volume": 100, // 0 to 100
//  "addmode": "play", // append, play(default)
//  "time": 0,
//  "media": {
//    "service": "youtube", // local, twitch...
//    //"file": "",
//    "http": "https://www.youtube.com/watch?v=fWNaR-rxAic&ab_channel=CarlyRaeJepsenVEVO",
//  }
//}