POST http://localhost:3000/remote
Content-Type: application/json

{
    "action": "next",
    "volume": 100,
    "playlist": "clearall",
    "media": {
        "service": "youtube",
        "position": "end"
    }
}

//{
//  "action": "pause", // pause, play, next, previous, stop
//  "volume": 100, // 0 to 100
//  "time": 0,
//  "playlist": "clearall",
//  "media": {
//    "position": "end", // now, next
//    "service": "youtube", // local, twitch...
//    "url": "https://www.youtube.com/watch?v=fWNaR-rxAic&ab_channel=CarlyRaeJepsenVEVO",
//  }
//}